package fr.blocblocthebloc.busutilities.procedures;

import net.minecraft.world.level.LevelAccessor;

import fr.blocblocthebloc.busutilities.network.BusutilitiesModVariables;

public class ControleVariableChangeProcedure {
	public static void execute(LevelAccessor world) {
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_9 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_8;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_9 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_8;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_9 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_8;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_9 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_8;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_8 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_7;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_8 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_7;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_8 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_7;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_8 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_7;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_7 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_6;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_7 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_6;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_7 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_6;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_7 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_6;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_6 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_5;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_6 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_5;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_6 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_5;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_6 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_5;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_5 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_4;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_5 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_4;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_5 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_4;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_5 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_4;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_4 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_3;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_4 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_3;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_4 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_3;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_4 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_3;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_3 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_2;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_3 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_2;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_3 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_2;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_3 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_2;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_2 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_1;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_2 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_1;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_2 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_1;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_2 = BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_1;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_name_1 = BusutilitiesModVariables.MapVariables.get(world).last_ticket_use_name;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_text_1 = BusutilitiesModVariables.MapVariables.get(world).last_ticket_use_text;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_date_1 = BusutilitiesModVariables.MapVariables.get(world).last_ticket_use_date;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
		BusutilitiesModVariables.MapVariables.get(world).ticket_use_heure_1 = BusutilitiesModVariables.MapVariables.get(world).last_ticket_use_heure;
		BusutilitiesModVariables.MapVariables.get(world).syncData(world);
	}
}
